# Simple workflow for deploying static content to GitHub Pages
name: Build dll

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build app for release
        run: msbuild "Project Reboot 3.0.sln" -t:rebuild -verbosity:diag -property:Configuration=Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          path: '.\x64\Release'
